var alphatJayatillekeWallFunctionFvPatchScalarField_8H =
[
    [ "alphatJayatillekeWallFunctionFvPatchScalarField", "classFoam_1_1compressible_1_1alphatJayatillekeWallFunctionFvPatchScalarField.html", "classFoam_1_1compressible_1_1alphatJayatillekeWallFunctionFvPatchScalarField" ]
];