var dir_c07a5c0a0a3eae515da32d97e52e4410 =
[
    [ "interfaceHeatResistance.C", "src_2phaseSystemModels_2multiphaseInter_2phasesSystem_2massTransferModels_2interfaceHeatResistance_2interfaceHeatResistance_8C.html", null ],
    [ "interfaceHeatResistance.H", "src_2phaseSystemModels_2multiphaseInter_2phasesSystem_2massTransferModels_2interfaceHeatResistance_2interfaceHeatResistance_8H.html", "src_2phaseSystemModels_2multiphaseInter_2phasesSystem_2massTransferModels_2interfaceHeatResistance_2interfaceHeatResistance_8H" ]
];