var dir_9776c82478826e2d976040db156e68ea =
[
    [ "powerLaw.C", "TurbulenceModels_2turbulenceModels_2laminar_2generalizedNewtonian_2generalizedNewtonianViscosityModels_2powerLaw_2powerLaw_8C.html", "TurbulenceModels_2turbulenceModels_2laminar_2generalizedNewtonian_2generalizedNewtonianViscosityModels_2powerLaw_2powerLaw_8C" ],
    [ "powerLaw.H", "TurbulenceModels_2turbulenceModels_2laminar_2generalizedNewtonian_2generalizedNewtonianViscosityModels_2powerLaw_2powerLaw_8H.html", "TurbulenceModels_2turbulenceModels_2laminar_2generalizedNewtonian_2generalizedNewtonianViscosityModels_2powerLaw_2powerLaw_8H" ]
];