var dir_a8eb0b53659ed64f9e05302a4c666aa8 =
[
    [ "TomiyamaWallLubrication.C", "reactingEuler_2multiphaseSystem_2interfacialModels_2wallLubricationModels_2TomiyamaWallLubrication_2TomiyamaWallLubrication_8C.html", "reactingEuler_2multiphaseSystem_2interfacialModels_2wallLubricationModels_2TomiyamaWallLubrication_2TomiyamaWallLubrication_8C" ],
    [ "TomiyamaWallLubrication.H", "reactingEuler_2multiphaseSystem_2interfacialModels_2wallLubricationModels_2TomiyamaWallLubrication_2TomiyamaWallLubrication_8H.html", "reactingEuler_2multiphaseSystem_2interfacialModels_2wallLubricationModels_2TomiyamaWallLubrication_2TomiyamaWallLubrication_8H" ]
];