var dir_ec88675e84102966a5cb4791f54bceca =
[
    [ "constantLiftCoefficient.C", "reactingEuler_2multiphaseSystem_2interfacialModels_2liftModels_2constantLiftCoefficient_2constantLiftCoefficient_8C.html", "reactingEuler_2multiphaseSystem_2interfacialModels_2liftModels_2constantLiftCoefficient_2constantLiftCoefficient_8C" ],
    [ "constantLiftCoefficient.H", "reactingEuler_2multiphaseSystem_2interfacialModels_2liftModels_2constantLiftCoefficient_2constantLiftCoefficient_8H.html", "reactingEuler_2multiphaseSystem_2interfacialModels_2liftModels_2constantLiftCoefficient_2constantLiftCoefficient_8H" ]
];