var dir_c3ec1872210f0c422618dedb76fd51b1 =
[
    [ "SyamlalOBrien.C", "multiphaseEuler_2multiphaseSystem_2interfacialModels_2dragModels_2SyamlalOBrien_2SyamlalOBrien_8C.html", "multiphaseEuler_2multiphaseSystem_2interfacialModels_2dragModels_2SyamlalOBrien_2SyamlalOBrien_8C" ],
    [ "SyamlalOBrien.H", "multiphaseEuler_2multiphaseSystem_2interfacialModels_2dragModels_2SyamlalOBrien_2SyamlalOBrien_8H.html", "multiphaseEuler_2multiphaseSystem_2interfacialModels_2dragModels_2SyamlalOBrien_2SyamlalOBrien_8H" ]
];