var dir_7954926a95a1cf9a63ccc173c6db88de =
[
    [ "GidaspowSchillerNaumann.C", "twoPhaseEuler_2twoPhaseSystem_2interfacialModels_2dragModels_2GidaspowSchillerNaumann_2GidaspowSchillerNaumann_8C.html", "twoPhaseEuler_2twoPhaseSystem_2interfacialModels_2dragModels_2GidaspowSchillerNaumann_2GidaspowSchillerNaumann_8C" ],
    [ "GidaspowSchillerNaumann.H", "twoPhaseEuler_2twoPhaseSystem_2interfacialModels_2dragModels_2GidaspowSchillerNaumann_2GidaspowSchillerNaumann_8H.html", "twoPhaseEuler_2twoPhaseSystem_2interfacialModels_2dragModels_2GidaspowSchillerNaumann_2GidaspowSchillerNaumann_8H" ]
];