var dir_b0a74f56c151a0d905a130de42a6b451 =
[
    [ "compat", "dir_51c1e87bfaee7ab1ba5986fd72b2309a.html", "dir_51c1e87bfaee7ab1ba5986fd72b2309a" ],
    [ "IPBstreams.C", "IPBstreams_8C.html", null ],
    [ "IPstream.H", "IPstream_8H.html", "IPstream_8H" ],
    [ "IPstreams.C", "IPstreams_8C.html", null ],
    [ "OPBstreams.C", "OPBstreams_8C.html", null ],
    [ "OPstream.H", "OPstream_8H.html", "OPstream_8H" ],
    [ "OPstreams.C", "OPstreams_8C.html", null ],
    [ "Pstream.C", "Pstream_8C.html", "Pstream_8C" ],
    [ "Pstream.H", "Pstream_8H.html", "Pstream_8H" ],
    [ "PstreamBuffers.C", "PstreamBuffers_8C.html", "PstreamBuffers_8C" ],
    [ "PstreamBuffers.H", "PstreamBuffers_8H.html", "PstreamBuffers_8H" ],
    [ "PstreamReduceOps.H", "PstreamReduceOps_8H.html", "PstreamReduceOps_8H" ],
    [ "UIPstream.H", "UIPstream_8H.html", "UIPstream_8H" ],
    [ "UIPstreamBase.C", "UIPstreamBase_8C.html", "UIPstreamBase_8C" ],
    [ "UOPstream.H", "UOPstream_8H.html", "UOPstream_8H" ],
    [ "UOPstreamBase.C", "UOPstreamBase_8C.html", null ],
    [ "UPstream.C", "OpenFOAM_2db_2IOstreams_2Pstreams_2UPstream_8C.html", "OpenFOAM_2db_2IOstreams_2Pstreams_2UPstream_8C" ],
    [ "UPstream.H", "UPstream_8H.html", "UPstream_8H" ],
    [ "UPstreamCommsStruct.C", "UPstreamCommsStruct_8C.html", "UPstreamCommsStruct_8C" ],
    [ "UPstreamFile.H", "UPstreamFile_8H.html", "UPstreamFile_8H" ],
    [ "UPstreamReduceOffsets.H", "UPstreamReduceOffsets_8H.html", "UPstreamReduceOffsets_8H" ],
    [ "UPstreamTraits.H", "UPstreamTraits_8H.html", "UPstreamTraits_8H" ],
    [ "UPstreamWindow.H", "UPstreamWindow_8H.html", "UPstreamWindow_8H" ]
];