var dir_8d6486794a0e36c4502c463fb39e7a58 =
[
    [ "BrunDrippingInjection.C", "regionModels_2surfaceFilmModels_2submodels_2kinematic_2injectionModel_2BrunDrippingInjection_2BrunDrippingInjection_8C.html", "regionModels_2surfaceFilmModels_2submodels_2kinematic_2injectionModel_2BrunDrippingInjection_2BrunDrippingInjection_8C" ],
    [ "BrunDrippingInjection.H", "regionModels_2surfaceFilmModels_2submodels_2kinematic_2injectionModel_2BrunDrippingInjection_2BrunDrippingInjection_8H.html", "regionModels_2surfaceFilmModels_2submodels_2kinematic_2injectionModel_2BrunDrippingInjection_2BrunDrippingInjection_8H" ]
];