var dir_e208154bc20971afa961f9a77f15b167 =
[
    [ "wallLubricationModel.C", "twoPhaseEuler_2twoPhaseSystem_2interfacialModels_2wallLubricationModels_2wallLubricationModel_2wallLubricationModel_8C.html", "twoPhaseEuler_2twoPhaseSystem_2interfacialModels_2wallLubricationModels_2wallLubricationModel_2wallLubricationModel_8C" ],
    [ "wallLubricationModel.H", "twoPhaseEuler_2twoPhaseSystem_2interfacialModels_2wallLubricationModels_2wallLubricationModel_2wallLubricationModel_8H.html", "twoPhaseEuler_2twoPhaseSystem_2interfacialModels_2wallLubricationModels_2wallLubricationModel_2wallLubricationModel_8H" ]
];