var group__grpSurfaceUtilities =
[
    [ "surfaceAdd.C", "surfaceAdd_8C.html", null ],
    [ "surfaceBooleanFeatures.C", "surfaceBooleanFeatures_8C.html", null ],
    [ "surfaceCheck.C", "surfaceCheck_8C.html", null ],
    [ "surfaceClean.C", "surfaceClean_8C.html", null ],
    [ "surfaceCoarsen.C", "surfaceCoarsen_8C.html", null ],
    [ "surfaceConvert.C", "surfaceConvert_8C.html", null ],
    [ "surfaceFeatureConvert.C", "surfaceFeatureConvert_8C.html", null ],
    [ "surfaceFeatureExtract.C", "surfaceFeatureExtract_8C.html", null ],
    [ "surfaceFind.C", "surfaceFind_8C.html", null ],
    [ "surfaceHookUp.C", "surfaceHookUp_8C.html", null ],
    [ "surfaceInertia.C", "surfaceInertia_8C.html", null ],
    [ "surfaceInflate.C", "surfaceInflate_8C.html", null ],
    [ "surfaceLambdaMuSmooth.C", "surfaceLambdaMuSmooth_8C.html", null ],
    [ "surfaceMeshConvert.C", "surfaceMeshConvert_8C.html", null ],
    [ "surfaceMeshExport.C", "surfaceMeshExport_8C.html", null ],
    [ "surfaceMeshExtract.C", "surfaceMeshExtract_8C.html", null ],
    [ "surfaceMeshImport.C", "surfaceMeshImport_8C.html", null ],
    [ "surfaceMeshInfo.C", "surfaceMeshInfo_8C.html", null ],
    [ "surfaceOrient.C", "surfaceOrient_8C.html", null ],
    [ "surfacePatch.C", "applications_2utilities_2surface_2surfacePatch_2surfacePatch_8C.html", null ],
    [ "surfacePointMerge.C", "surfacePointMerge_8C.html", null ],
    [ "surfaceRedistributePar.C", "surfaceRedistributePar_8C.html", null ],
    [ "surfaceRefineRedGreen.C", "surfaceRefineRedGreen_8C.html", null ],
    [ "surfaceSplitByPatch.C", "surfaceSplitByPatch_8C.html", null ],
    [ "surfaceSplitByTopology.C", "surfaceSplitByTopology_8C.html", null ],
    [ "surfaceSplitNonManifolds.C", "surfaceSplitNonManifolds_8C.html", null ],
    [ "surfaceSubset.C", "surfaceSubset_8C.html", null ],
    [ "surfaceToPatch.C", "surfaceToPatch_8C.html", null ],
    [ "surfaceTransformPoints.C", "surfaceTransformPoints_8C.html", null ],
    [ "chemkinToFoam.C", "chemkinToFoam_8C.html", null ]
];