var reactingEuler_2twoPhaseCompressibleTurbulenceModels_2kineticTheoryModels_2conductivityModel_2Gidaspow_2GidaspowConductivity_8H =
[
    [ "Gidaspow", "classFoam_1_1kineticTheoryModels_1_1conductivityModels_1_1Gidaspow.html", "classFoam_1_1kineticTheoryModels_1_1conductivityModels_1_1Gidaspow" ]
];