var reactingEuler_2multiphaseSystem_2interfacialModels_2turbulentDispersionModels_2noTurbulentDispersion_2noTurbulentDispersion_8C =
[
    [ "defineTypeNameAndDebug", "reactingEuler_2multiphaseSystem_2interfacialModels_2turbulentDispersionModels_2noTurbulentDispersion_2noTurbulentDispersion_8C.html#aa3caae05b12e507e82e00ae8c133708d", null ],
    [ "addToRunTimeSelectionTable", "reactingEuler_2multiphaseSystem_2interfacialModels_2turbulentDispersionModels_2noTurbulentDispersion_2noTurbulentDispersion_8C.html#aa3ed10a94b4fa4cad48520a657d2cd15", null ]
];